[versions]
biometric-ktx = "1.2.0-alpha05"
json = "20210307"
kotlin = "1.8.10"
java = "1.8"
gradle-plugin = "7.4.0"
dependency-license-report = "2.4"
identity-credential = "20231002"
identity-credential-android = "20231002"
cbor = "4.5.2"
cose = "1.1.0"
bouncy-castle = "1.77"
junit = "4.13.2"
junit-android = "1.1.5"
mockk = "1.13.5"
espresso-core = "3.5.1"
mavenPublish = "0.25.3"
dependencycheck = "9.0.9"
sonarqube = "4.4.1.3373"

[libraries]
biometric-ktx = { module = "androidx.biometric:biometric-ktx", version.ref = "biometric-ktx" }
identity-credential = { module = "com.android.identity:identity-credential", version.ref = "identity-credential" }
android-identity-credential = { module = "com.android.identity:identity-credential-android", version.ref = "identity-credential-android" }
cbor = { module = "com.upokecenter:cbor", version.ref = "cbor" }
cose = { module = "com.augustcellars.cose:cose-java", version.ref = "cose" }
bouncy-castle-prov = { module = "org.bouncycastle:bcprov-jdk18on", version.ref = "bouncy-castle" }
bouncy-castle-pkix = { module = "org.bouncycastle:bcpkix-jdk18on", version.ref = "bouncy-castle" }
json = { module = "org.json:json", version.ref = "json" }
junit = { module = "junit:junit", version.ref = "junit" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
android-junit = { module = "androidx.test.ext:junit", version.ref = "junit-android" }
espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso-core" }

[plugins]
android-library = { id = "com.android.library", version.ref = "gradle-plugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
dokka = { id = "org.jetbrains.dokka", version.ref = "kotlin" }
dependency-license-report = { id = "com.github.jk1.dependency-license-report", version.ref = "dependency-license-report" }
dependencycheck = { id = "org.owasp.dependencycheck", version.ref = "dependencycheck" }
maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "mavenPublish" }
sonarqube = { id = "org.sonarqube", version.ref = "sonarqube" }
